title: iamsuman
email: sumn2u@gmail.com
description: Making web a Better Place
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Suman Kunwar # add your name
author-pic: avatar.jpg
about-author: I'm Suman, experienced javascript developer, open source enthusiast and interested to help lower the barrier for people to contribute to open source in general

# Contact links
email: sumn2u@gmail.com # Add your Email address
phone: +1 201 680 8700 # Add your Phone number
website: https://humanassistai.com/  # Add your website, do not add http://
linkedin: sumn2u # Add your Linkedin handle
github: sumn2u # Add your Github handle
twitter: '@sumn2u' # Add your Twitter handle
facebook: humanassistai # Add your Facebook handle
instagram: iamsumankunwar # Add your Instagram handle
pinterest: sumankunwar # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: iamsuman # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
